# Generated by Django 2.2.1 on 2019-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='weight',
            field=models.IntegerField(default=5),
        ),
    ]
